-- Carga de estados y observaciones en el seguimiento de necesidades.
-- La observación del archivo se almacena en detalle_accion.
-- Requiere haber ejecutado sql/04_seguimiento_necesidades.sql
-- y sql/06_actualizar_dominios_seguimiento.sql.

begin;

create temporary table carga_seguimiento_necesidades (
  necesidad_id bigint primary key,
  estado_actual text not null,
  detalle_accion text not null
) on commit drop;

insert into carga_seguimiento_necesidades (
  necesidad_id,
  estado_actual,
  detalle_accion
)
values
  (1, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022.'),
  (7, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (9, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-02, y señala a SAID como unidad responsable de formulación.'),
  (10, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (13, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La observación original indica descarte por bajo caudal en época seca.'),
  (15, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. Existe inconsistencia entre el nombre «tanque Entierrillos», el sistema ME-A-07 y la descripción «Colinas de Montealegre».'),
  (16, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-03, y señala a SAID como unidad responsable de formulación.'),
  (17, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022.'),
  (19, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La observación original indica «En ejecución». No debe marcarse como Necesidad Resuelta hasta contar con cierre o recepción.'),
  (20, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022.'),
  (21, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (22, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La mención «posiblemente ya fue ejecutado» no constituye evidencia de cierre.'),
  (23, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022.'),
  (24, 'Iniciativa enviada a la Dirección de Planificación', 'La iniciativa fue remitida a Planificación mediante UEN-OS-GAM-2022-00068, adenda de UEN-OSEP-GAM-2022-00067. La anotación «Ejecutado» no está acompañada en el expediente revisado por acta de recepción, informe final u oficio de cierre.'),
  (25, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante UEN-OSEP-GAM-2022-00245, de 8 de diciembre de 2022, dirigido a la Dirección de Planificación Estratégica. La ficha adjunta trata la inestabilidad del talud que amenaza el tanque cisterna y la estación de bombeo de Barbacoas.'),
  (26, 'Iniciativa trasladada a SAID', 'El oficio UEN-OS-GAM-2026-00023 no está incluido en el expediente documental revisado; el estado se conserva únicamente de forma provisional.'),
  (27, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (29, 'Iniciativa enviada a la Dirección de Planificación', 'UEN-OSEP-GAM-2022-00080 acredita el envío a Planificación de una necesidad de tratamiento de potabilización en El Guarco. La equivalencia con esta fila es probable, pero debe verificarse contra la plantilla adjunta original.'),
  (30, 'Iniciativa enviada a la Dirección de Planificación', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (31, 'Iniciativa enviada a la Dirección de Planificación', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (32, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (33, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-18, y señala a SAID como unidad responsable de formulación.'),
  (34, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-22, y señala a SAID como unidad responsable de formulación.'),
  (35, 'Iniciativa enviada a la Dirección de Planificación', 'La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código AB 8, y señala a SAID como unidad responsable de formulación. Se recomienda mantener el hito de Planificación hasta localizar el oficio de asignación o traslado a SAID.'),
  (37, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-13, y señala a SAID como unidad responsable de formulación.'),
  (40, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-11, y señala a SAID como unidad responsable de formulación.'),
  (41, 'Iniciativa enviada a la Dirección de Planificación', 'La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-16, y señala a SAID como unidad responsable de formulación. Se recomienda mantener el hito de Planificación hasta localizar el oficio de asignación o traslado a SAID.'),
  (42, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-20, y señala a SAID como unidad responsable de formulación.'),
  (43, 'Iniciativa enviada a la Dirección de Planificación', 'La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-26, y señala a SAID como unidad responsable de formulación. Se recomienda mantener el hito de Planificación hasta localizar el oficio de asignación o traslado a SAID.'),
  (44, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022. La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-09, y señala a SAID como unidad responsable de formulación.'),
  (45, 'Conceptualizado como una idea', 'Fase: idea de proyecto. Responsable: SAID. Puntaje: 2,06. Referencia: oficio SG-GSGAM-2023-01104. El oficio SG-GSGAM-2023-01104 no está incluido en el expediente documental revisado; el estado se conserva únicamente de forma provisional.'),
  (46, 'Iniciativa enviada a la Dirección de Planificación', 'La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-E-01, y señala a SAID como unidad responsable de formulación. Se recomienda mantener el hito de Planificación hasta localizar el oficio de asignación o traslado a SAID.'),
  (48, 'Iniciativa enviada a la Dirección de Planificación', 'La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código GAM-A-27, y señala a SAID como unidad responsable de formulación. Se recomienda mantener el hito de Planificación hasta localizar el oficio de asignación o traslado a SAID.'),
  (49, 'Iniciativa enviada a la Dirección de Planificación', 'La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código Sin código consignado, y señala a SAID como unidad responsable de formulación. Se recomienda mantener el hito de Planificación hasta localizar el oficio de asignación o traslado a SAID.'),
  (51, 'Iniciativa enviada a la Dirección de Planificación', 'La matriz de la Dirección de Planeamiento Físico y Gestión de Cartera, asociada a PRE-PLA-2026-00534, registra esta iniciativa como «Idea de proyecto», código Sin código consignado, y señala a SAID como unidad responsable de formulación. Se recomienda mantener el hito de Planificación hasta localizar el oficio de asignación o traslado a SAID.'),
  (55, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Apoyo: UEN Programación y Control, oficio UEN-PyDPP-GAM-2016-000459. Licitaciones relacionadas: 2024LY-000029-0021400001 y 2023LY-000013-0021400001 estabilización. Ruta propuesta: estabilización. No requiere solicitud de necesidad de proyecto. Ejecución: LC, requiere 1 Ejecutivo Avanzado y 2 GE. No se encontró oficio de traslado; la clasificación propuesta se basa en que la propia revisión indica que no requiere una nueva necesidad de proyecto. Corrección documental: la referencia observada en la ficha es UEN-PyDPP-GAM-2016-00459. La ficha de 2022 indica que fue contestada mediante UEN-PC-2016-2221 sin gestión realizada; debe citarse únicamente como antecedente histórico y no como prueba de traslado.'),
  (56, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad. Apoyo requerido: PyC para diseño o revisión hidráulica. Ruta propuesta: diseño / PyC. No requiere solicitud de necesidad de proyecto. Ejecución: Diseño PyC / LC. No se encontró oficio de traslado; la clasificación propuesta se basa en que la propia revisión indica que no requiere una nueva necesidad de proyecto.'),
  (57, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (58, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (59, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (60, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (61, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (62, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Valorar ejecución mediante convenio marco 2024LY-000029-0021400001, según alcance aplicable. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (63, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Valorar ejecución mediante convenio marco 2024LY-000029-0021400001, según alcance aplicable. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (64, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Valorar ejecución mediante convenio marco 2024LY-000029-0021400001, según alcance aplicable. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (65, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Valorar ejecución mediante convenio marco 2024LY-000029-0021400001, según alcance aplicable. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (66, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (67, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Apoyo: UEN Programación y Control, oficio UEN-PyDPP-GAM-2016-000459. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Valorar ejecución mediante convenio marco 2024LY-000029-0021400001. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM. Corrección documental: la referencia observada en la ficha es UEN-PyDPP-GAM-2016-00459. La ficha de 2022 indica que fue contestada mediante UEN-PC-2016-2221 sin gestión realizada; debe citarse únicamente como antecedente histórico y no como prueba de traslado.'),
  (68, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (69, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (70, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (71, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (72, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: cantidad y continuidad. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Valorar ejecución mediante convenio marco según alcance aplicable. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (73, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (74, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (75, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Valorar ejecución mediante convenio marco 2024LY-000029-0021400001. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (76, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (77, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: cantidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Zona / LC. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (78, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Zona / LC. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (79, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (80, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (81, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Zona / LC. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (82, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: cantidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (83, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (84, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa. Corrección documental: la referencia observada en la ficha es UEN-PyDPP-GAM-2016-00459. La ficha de 2022 indica que fue contestada mediante UEN-PC-2016-2221 sin gestión realizada; debe citarse únicamente como antecedente histórico y no como prueba de traslado.'),
  (85, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (86, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Apoyo: UEN Programación y Control, oficio UEN-PyDPP-GAM-2016-000459. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Zona / LC. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM. Corrección documental: la referencia observada en la ficha es UEN-PyDPP-GAM-2016-00459. La ficha de 2022 indica que fue contestada mediante UEN-PC-2016-2221 sin gestión realizada; debe citarse únicamente como antecedente histórico y no como prueba de traslado.'),
  (87, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad y continuidad. Apoyo: UEN Programación y Control, oficio UEN-PyDPP-GAM-2016-000459. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM. Corrección documental: la referencia observada en la ficha es UEN-PyDPP-GAM-2016-00459. La ficha de 2022 indica que fue contestada mediante UEN-PC-2016-2221 sin gestión realizada; debe citarse únicamente como antecedente histórico y no como prueba de traslado.'),
  (88, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (89, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitaciones relacionadas: 2024LY-000029-0021400001 y 2023LY-000013-0021400001 estabilización. Ruta propuesta: estabilización. No requiere solicitud de necesidad de proyecto. Ejecución: LC, requiere 1 Ejecutivo Avanzado y 2 GE. No se encontró oficio de traslado; la clasificación propuesta se basa en que la propia revisión indica que no requiere una nueva necesidad de proyecto.'),
  (90, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (91, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (92, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: estabilización. No requiere solicitud de necesidad de proyecto. Valorar ejecución mediante contratación de estabilización 2023LY-000013-0021400001. Ejecución: LC, requiere 1 Ejecutivo Avanzado y 2 GE. No se encontró oficio de traslado; la clasificación propuesta se basa en que la propia revisión indica que no requiere una nueva necesidad de proyecto.'),
  (93, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Valorar ejecución mediante convenio marco según alcance aplicable. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (94, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (95, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad, cantidad y continuidad. Licitación vigente: 2024LY-000029-0021400001 / Proyecto de inversión. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (96, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (97, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (98, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (99, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Ejecución: PyC diseño y términos de referencia / Zona / LC. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (100, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (101, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (102, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: cantidad y continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (103, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (104, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (105, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (106, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (107, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (108, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad y cantidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (109, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: cantidad y continuidad. Licitación vigente: 2024LY-000029-0021400001. Ruta propuesta: convenio marco. No requiere solicitud de necesidad de proyecto. Requiere apoyo de PyC para diseño. Ejecución: PyC diseño y términos de referencia / Mantenimiento Civil. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (110, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (112, 'Iniciativa enviada a la Dirección de Planificación', 'La planta está incluida en la ficha institucional «Sistemas de tratamiento de aguas residuales en las Plantas Potabilizadoras de AyA», remitida a Planificación mediante UEN-OSEP-GAM-2022-00078. El antecedente correcto es UEN-PyDPP-GAM-2016-00459, no UEN-PyDPP-GAM-2016-000459; la propia ficha indica que fue respondido por UEN-PC-2016-2221 sin gestión realizada, por lo que no acredita traslado a SAID.'),
  (113, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad. Ruta propuesta: licitación mayor. No requiere solicitud de necesidad de proyecto. Licitación en trámite por Plantas. Ejecución: Plantas. No se encontró oficio de traslado; la clasificación propuesta se basa en que la propia revisión indica que no requiere una nueva necesidad de proyecto.'),
  (114, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad. Apoyo: Optimización / RANC. Ruta propuesta: Optimización / RANC. No requiere solicitud de necesidad de proyecto. Ejecución: OS/RANC. No se encontró oficio de traslado; la clasificación propuesta se basa en que la propia revisión indica que no requiere una nueva necesidad de proyecto.'),
  (115, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: calidad. Ruta propuesta: licitación mayor. No requiere solicitud de necesidad de proyecto. Verificar alcance en licitación vigente de Plantas. Ejecución: Plantas. No se encontró oficio de traslado; la clasificación propuesta se basa en que la propia revisión indica que no requiere una nueva necesidad de proyecto.'),
  (116, 'La Iniciativa puede ser asumida con presupuesto operativo', 'Impacto principal: continuidad. Ruta propuesta: por definir / propuesta de contratación. No requiere solicitud de necesidad de proyecto. Ejecución: PyD / Contratación. No se encontró oficio de traslado; la clasificación propuesta se basa en que la propia revisión indica que no requiere una nueva necesidad de proyecto.'),
  (117, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 66; Zona: Zona 3; Pri.: Urgente; Plazo: Corto; Costo: Mediano; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (118, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (119, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (120, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (121, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 70; Zona: Zona 3; Pri.: Urgente; Plazo: Corto; Costo: Mediano; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (122, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (123, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (124, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (125, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (126, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (127, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (128, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (129, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (130, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (131, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (132, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (133, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (134, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (135, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (136, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 85; Zona: Zona 3; Pri.: Urgente; Plazo: Corto; Costo: Bajo; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (137, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 86; Zona: Zona 3; Pri.: Importante; Plazo: Corto a mediano; Costo: Mediano a alto; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (138, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (139, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (140, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (141, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (142, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 91; Zona: Zona 3; Pri.: Importante; Plazo: Corto a mediano; Costo: Mediano; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (143, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (144, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (145, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (146, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 95; Zona: Zona 3; Pri.: Estratégico; Plazo: Mediano; Costo: Alto; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (147, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (148, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (149, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (150, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (151, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (152, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (153, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (154, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (155, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (156, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (157, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (159, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (161, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (162, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (163, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 112; Zona: Zona 4; Pri.: Estratégico; Plazo: Corto a mediano; Costo: Bajo; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (164, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (165, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (166, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (167, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (168, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (169, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 118; Zona: Zona 5; Pri.: Urgente; Plazo: Corto; Costo: Mediano; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (170, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (171, 'Iniciativa trasladada a SAID', 'ID 120; Zona: Zona 5; Pri.: Urgente; Plazo: Mediano; Costo: Alto; Estado: Pendiente. El oficio UEN-OS-GAM-2026-00023 no está incluido en el expediente documental revisado; el estado se conserva únicamente de forma provisional.'),
  (172, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (173, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (174, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (175, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (176, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (177, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (178, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (179, 'La Iniciativa puede ser asumida con presupuesto operativo', 'ID 128; Zona: Zona 5; Pri.: Importante; Plazo: Corto; Costo: Bajo; Estado: Pendiente. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (180, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (181, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (182, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (183, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (184, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (185, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (186, 'Iniciativa enviada a la Dirección de Planificación', 'Traslado formal acreditado mediante el memorando UEN-OSEP-GAM-2022-00067, dirigido a Planificación. La iniciativa se identifica en el Informe Iniciativas GAM y en el Listado de iniciativas GAM como parte de la cartera remitida en 2022.'),
  (187, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (188, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (189, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (190, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (191, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (192, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (193, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (194, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (195, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (197, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (198, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (199, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (200, 'La Iniciativa puede ser asumida con presupuesto operativo', 'El oficio SG-GSD-2025-00320 no está incluido en el expediente documental revisado; el estado se conserva únicamente de forma provisional.'),
  (201, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (202, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (203, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (205, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (208, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (209, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (213, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (214, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (215, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (216, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (217, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (219, 'La Iniciativa puede ser asumida con presupuesto operativo', 'El documento no especifica cantidad de fugas, caudal perdido, alcance, costo ni plazo. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (220, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (221, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (222, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (223, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (224, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (225, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (227, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (228, 'La Iniciativa puede ser asumida con presupuesto operativo', 'El documento no identifica el sistema, el sector exacto, el caudal, el costo ni el alcance técnico. No se encontró un oficio que la traslade a Planificación, SAID, Presidencia o Subgerencia GAM.'),
  (229, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (231, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (232, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (233, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (234, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (235, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.'),
  (236, 'Conceptualizado como una idea', 'Revisión documental: no se identificó un oficio dirigido a Planificación, SAID, Presidencia o Subgerencia GAM que formalice el traslado de esta iniciativa.');

-- Validaciones previas: cualquier inconsistencia cancela toda la transacción.
do $validacion$
declare
  v_ids_inexistentes text;
  v_estados_invalidos text;
begin
  select string_agg(c.necesidad_id::text, ', ' order by c.necesidad_id)
    into v_ids_inexistentes
  from carga_seguimiento_necesidades as c
  where not exists (
    select 1
    from public.necesidades as n
    where n.id = c.necesidad_id
  );

  if v_ids_inexistentes is not null then
    raise exception
      'Carga cancelada. Estos ID no existen en necesidades: %',
      v_ids_inexistentes;
  end if;

  select string_agg(distinct c.estado_actual, ' | ' order by c.estado_actual)
    into v_estados_invalidos
  from carga_seguimiento_necesidades as c
  where c.estado_actual not in (
    'Conceptualizado como una idea',
    'En Ejecución',
    'Incorporada al BPIP o convertida en proyecto',
    'Iniciativa enviada a la Dirección de Planificación',
    'Iniciativa trasladada a SAID',
    'Trasladado a Presidencia',
    'Trasladado a Subgerencia GAM',
    'Necesidad Resuelta',
    'La Iniciativa puede ser asumida con presupuesto operativo',
    'Descartada o no viable',
    'Suspendida o pendiente de información'
  );

  if v_estados_invalidos is not null then
    raise exception
      'Carga cancelada. Estados fuera del dominio: %',
      v_estados_invalidos;
  end if;
end;
$validacion$;

insert into public.necesidades_seguimiento (
  necesidad_id,
  estado_actual,
  detalle_accion
)
select
  necesidad_id,
  estado_actual,
  detalle_accion
from carga_seguimiento_necesidades
on conflict (necesidad_id) do update
set
  estado_actual = excluded.estado_actual,
  detalle_accion = excluded.detalle_accion,
  updated_at = now();

commit;

-- Verificación de los registros cargados.
select
  n.id,
  n.objetivo_de_la_iniciativa,
  s.estado_actual,
  s.detalle_accion,
  s.updated_at
from public.necesidades_seguimiento as s
join public.necesidades as n
  on n.id = s.necesidad_id
where s.necesidad_id in (
  1,
  7,
  9,
  10,
  13,
  15,
  16,
  17,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  37,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  48,
  49,
  51,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  159,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  205,
  208,
  209,
  213,
  214,
  215,
  216,
  217,
  219,
  220,
  221,
  222,
  223,
  224,
  225,
  227,
  228,
  229,
  231,
  232,
  233,
  234,
  235,
  236
)
order by n.id;
